### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Enigma37** [banteg/rarbg#8]
The RSS just stopped working today and only gives "500 Internal Server Error". 

This is the error I'm getting:

======== Running on http://0.0.0.0:4444 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/home/username/.local/lib/python3.5/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.5/dist-packages/rarbg-1.1.1-py3.5.egg/rarbg.py", line 102, in rarbg_rss
    params = dict(request.GET)
AttributeError: 'Request' object has no attribute 'GET'

**Comment by sergiogomespires** [comment]
Same problem here.

======== Running on http://0.0.0.0:4444 ========
(Press CTRL+C to quit)
[1] category=41, limit=100
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 109, in rarbg_rss
    return await api(params)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 74, in api
    await refresh_token()
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 61, in refresh_token
    data = await fetch_json(API_ENDPOINT, params={'get_token': 'get_token'})
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 55, in fetch_json
    return await resp.json()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

**Comment by StelArian** [comment]
Same here. About a week or so ago. Did someone test the solution suggested by @sergiogomespires ?

**Comment by aploleb** [comment]
I tried to add the app Id to rarbg.py but I don’t know python enough or something as it still got 500 error. Perhaps someone who knows python can advise me on the correct way.

**Comment by VirtuaWin** [comment]
Same as @aploleb. No idea where I should insert the app_id parameter. Can somebody help?

**Comment by banteg** [comment]
fixed in version 1.1.3, update with `pip install -U rarbg`

**Comment by angramainyu74** [comment]
Thanks for the fix!

I still saw an initial error with the first fetch, but after that everything worked fine.  My guess is it might be making the call before the the torrentapi site can use the token it just made.  Putting a sleep(2) in at the end of refresh_token() *seemed* to make it go away, but that would make sense if it a race condition on the torrentapi end.

**Comment by sergiogomespires** [comment]
Just updated to 1.1.3, however, i'm still getting the 500 Internal Server Error.

======== Running on http://0.0.0.0:4444 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 103, in rarbg_rss
    params = dict(request.GET)
AttributeError: 'Request' object has no attribute 'GET'

If i go back to 1.1.2 and replace the line on rarbg.py with
API_ENDPOINT = 'https://torrentapi.org/pubapi_v2.php'
with
API_ENDPOINT = 'https://torrentapi.org/pubapi_v2.php?app_id=github.com/banteg/rarbg'

i get a 500 server error the first time i try, however, after a refresh things behave normally:

======== Running on http://0.0.0.0:4444 ========
(Press CTRL+C to quit)
[1] category=41, limit=100
refresh token - hftu4p96si
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 109, in rarbg_rss
    return await api(params)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 76, in api
    data = await fetch_json(API_ENDPOINT, params=params)
  File "/usr/local/lib/python3.6/site-packages/rarbg.py", line 55, in fetch_json
    return await resp.json()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: '
[2] category=41, limit=100
[2] 100 results

It seems @angramainyu74 is right. There seems to be a need for a period of waiting between requesting the token and getting the token. @angramainyu74 where exactly do you add the sleep(2) line?

**Comment by EDanee** [comment]
Hi guys,

I'm still getting this error with the latest version.
Is it really fixed?
